//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LealBotBasics {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LealBotBasics.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;buildinfo&gt;&lt;version&gt;1.0.4&lt;/version&gt;&lt;build&gt;1&lt;/build&gt;&lt;date&gt;31/07/2017 00:00:00&lt;/date&gt;&lt;/buildinfo&gt;.
        /// </summary>
        internal static string buildinfo {
            get {
                return ResourceManager.GetString("buildinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;language name=&quot;en-US&quot;&gt;
        ///  &lt;NowPlaying&gt;Now Playing: **{0}** addeded by **{1}**!&lt;/NowPlaying&gt;
        ///  &lt;ActionSkip&gt;**{0}** skipped **{1}**.&lt;/ActionSkip&gt;
        ///  &lt;ActionVolume&gt;**{0}** changed the volume from **{1}** to **{2}**.&lt;/ActionVolume&gt;
        ///  &lt;ActionPause&gt;**{0}** paused the music.&lt;/ActionPause&gt;
        ///  &lt;ActionResume&gt;**{0}** resumed the music.&lt;/ActionResume&gt;
        ///  &lt;ActionClear&gt;**{0}** cleared the queue.&lt;/ActionClear&gt;
        ///  &lt;ActionRemove&gt;**{0}** removed **{1}** from the queue.&lt;/ActionRemove [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string lang_default {
            get {
                return ResourceManager.GetString("lang_default", resourceCulture);
            }
        }
    }
}
